// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Logs() {
  return window['go']['main']['App']['Logs']();
}

export function OpenInBrowser() {
  return window['go']['main']['App']['OpenInBrowser']();
}

export function OpenNodeJS() {
  return window['go']['main']['App']['OpenNodeJS']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Retry() {
  return window['go']['main']['App']['Retry']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}
