// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Logs():Promise<string>;

export function OpenInBrowser():Promise<void>;

export function OpenNodeJS():Promise<void>;

export function Quit():Promise<void>;

export function Retry():Promise<void>;

export function Status():Promise<main.status>;
