// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDSHUpdate() {
  return window['go']['main']['App']['CheckDSHUpdate']();
}

export function DSHVersion() {
  return window['go']['main']['App']['DSHVersion']();
}

export function DisableRemote() {
  return window['go']['main']['App']['DisableRemote']();
}

export function EnableRemote() {
  return window['go']['main']['App']['EnableRemote']();
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function Logs() {
  return window['go']['main']['App']['Logs']();
}

export function OpenInBrowser() {
  return window['go']['main']['App']['OpenInBrowser']();
}

export function OpenNodeJS() {
  return window['go']['main']['App']['OpenNodeJS']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RegenerateRemoteToken() {
  return window['go']['main']['App']['RegenerateRemoteToken']();
}

export function RemoteStatus() {
  return window['go']['main']['App']['RemoteStatus']();
}

export function Retry() {
  return window['go']['main']['App']['Retry']();
}

export function RevokeDevice(arg1) {
  return window['go']['main']['App']['RevokeDevice'](arg1);
}

export function SetAllowPrivileged(arg1) {
  return window['go']['main']['App']['SetAllowPrivileged'](arg1);
}

export function SetDSHVersion(arg1) {
  return window['go']['main']['App']['SetDSHVersion'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}
