// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AccountStatus():Promise<main.accountStatus>;

export function ActiveDevices():Promise<Array<main.deviceActivity>>;

export function CancelRemoteSetup():Promise<main.remoteSetupStatus>;

export function CheckDSHUpdate():Promise<main.dshUpdateInfo>;

export function DSHVersion():Promise<string>;

export function DisableRemote():Promise<void>;

export function EnableRemote():Promise<main.remoteStatus>;

export function EntitlementStatus():Promise<main.entitlementStatus>;

export function ListDevices():Promise<Array<main.deviceIdentity>>;

export function Logs():Promise<string>;

export function OpenInBrowser():Promise<void>;

export function OpenNodeJS():Promise<void>;

export function Quit():Promise<void>;

export function RefreshRemoteSetup():Promise<main.remoteSetupStatus>;

export function RegenerateRemoteToken():Promise<main.remoteStatus>;

export function RegisterLANPairing(arg1:string,arg2:string):Promise<main.remoteSetupStatus>;

export function RelayStatus():Promise<main.relayStatus>;

export function RemoteSetupStatus():Promise<main.remoteSetupStatus>;

export function RemoteStatus():Promise<main.remoteStatus>;

export function Retry():Promise<void>;

export function RevokeDevice(arg1:string):Promise<boolean>;

export function SetAllowPrivileged(arg1:boolean):Promise<void>;

export function SetDSHVersion(arg1:string):Promise<void>;

export function SignInAccount():Promise<main.accountStatus>;

export function SignOutAccount():Promise<main.accountStatus>;

export function StartRemoteSetup():Promise<main.remoteSetupStatus>;

export function Status():Promise<main.status>;

export function UninstallPreinstalledPlugin(arg1:string):Promise<boolean>;
